name: CI

on:
  pull_request:
    branches:
      - DevOps

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin' # Can be 'adopt', 'zulu', 'corretto', 'ibm', 'liberica', 'microsoft', or 'temurin'

    - name: Build
      run: |
        echo "Building the project..."
        # Replace with your build command, e.g., ./gradlew build
    - name: Test
      run: |
        echo "Running tests..."
        # Replace with your test command, e.g., ./gradlew test
    - name: Verify
      run: |
        echo "Verifying the build..."
        # Replace with your verification steps, e.g., ./gradlew verify
    - name: Notify GitHub of success
      if: success()
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Build succeeded, notifying GitHub..."
        gh api -X POST /repos/${{ github.repository }}/statuses/${{ github.sha }} \
          -f state=success \
          -f target_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          -f description="Build successful" \
          -f context="continuous-integration/github-actions"
    - name: Notify GitHub of failure
      if: failure()
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Build failed, notifying GitHub..."
        gh api -X POST /repos/${{ github.repository }}/statuses/${{ github.sha }} \
          -f state=failure \
          -f target_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          -f description="Build failed" \
          -f context="continuous-integration/github-actions"
